# Generated by Django 2.1.7 on 2021-06-11 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('FoodDelivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Deliveryboy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FoodDelivery.UserDetails')),
            ],
        ),
        migrations.AddField(
            model_name='chat',
            name='boy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.Deliveryboy'),
        ),
        migrations.AddField(
            model_name='chat',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FoodDelivery.UserDetails'),
        ),
    ]
