# Generated by Django 2.1.7 on 2021-07-01 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDelivery', '0002_userdetails_city'),
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('boy', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.Deliveryboy')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FoodDelivery.UserDetails')),
            ],
        ),
    ]
