# Generated by Django 2.1.7 on 2021-06-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='qty',
            field=models.IntegerField(default=1),
        ),
    ]
