# Generated by Django 2.1.7 on 2021-06-28 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('FoodDelivery', '0002_userdetails_city'),
        ('customer', '0003_reservation_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Caddress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cname', models.CharField(max_length=100)),
                ('caddress', models.CharField(max_length=1000)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='FoodDelivery.UserDetails')),
            ],
        ),
    ]
