# Generated by Django 2.1.7 on 2021-06-15 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_auto_20210615_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='seats',
            field=models.IntegerField(default=50),
        ),
    ]
