# Generated by Django 2.1.7 on 2021-06-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurants_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurants',
            name='since',
            field=models.IntegerField(default=1999),
        ),
        migrations.AlterField(
            model_name='restaurants',
            name='details',
            field=models.CharField(max_length=1500),
        ),
    ]
