# Generated by Django 2.1.7 on 2021-06-16 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20210616_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='since',
            field=models.CharField(default='1999', max_length=100),
        ),
    ]
