# Generated by Django 2.1.7 on 2021-06-16 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_restaurants_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestChefs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('img', models.ImageField(blank=True, upload_to='Restaurant_images')),
                ('resto', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant.Restaurants')),
            ],
        ),
    ]
