# Generated by Django 2.1.7 on 2021-06-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_restchefs'),
    ]

    operations = [
        migrations.AddField(
            model_name='restchefs',
            name='post',
            field=models.CharField(default='', max_length=200),
        ),
    ]
