# Generated by Django 2.1.7 on 2021-06-16 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_restchefs_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='restchefs',
            name='details',
            field=models.CharField(default='', max_length=500),
        ),
    ]
