# Generated by Django 2.1.7 on 2021-06-25 04:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_restchefs_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodimage',
            name='food',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.DO_NOTHING, to='restaurant.Food'),
        ),
    ]
